create table public.logos (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null check (category in ('animals', 'nature', 'food', 'objects', 'symbols', 'other')),
  storage_key text not null unique,
  image_url text not null,
  source_path text not null,
  content_hash text not null unique,
  byte_size bigint not null check (byte_size > 0),
  created_at timestamptz not null default now(),
  is_public boolean not null default true
);

create index logos_category_idx on public.logos (category) where is_public;
create index logos_name_idx on public.logos (lower(name)) where is_public;
create index logos_created_at_idx on public.logos (created_at desc) where is_public;

alter table public.logos enable row level security;

create policy "Public logos are readable"
on public.logos
for select
to anon, authenticated
using (is_public);

create or replace function public.get_logos(
  p_seed text,
  p_offset integer default 0,
  p_limit integer default 40,
  p_search text default '',
  p_category text default 'all',
  p_sort text default 'random'
)
returns table (
  id bigint,
  slug text,
  name text,
  category text,
  storage_key text,
  image_url text,
  byte_size bigint,
  created_at timestamptz
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    l.id,
    l.slug,
    l.name,
    l.category,
    l.storage_key,
    l.image_url,
    l.byte_size,
    l.created_at
  from public.logos as l
  where l.is_public
    and (p_category = 'all' or l.category = p_category)
    and (
      nullif(trim(p_search), '') is null
      or l.name ilike '%' || trim(p_search) || '%'
      or l.slug ilike '%' || trim(p_search) || '%'
    )
  order by
    case when p_sort = 'random' then md5(l.id::text || p_seed) end asc,
    case when p_sort = 'newest' then l.created_at end desc,
    case when p_sort = 'name' then lower(l.name) end asc,
    l.id asc
  offset greatest(p_offset, 0)
  limit least(greatest(p_limit, 1), 80);
$$;

create or replace function public.get_logo_count(
  p_search text default '',
  p_category text default 'all'
)
returns bigint
language sql
stable
security invoker
set search_path = public
as $$
  select count(*)
  from public.logos as l
  where l.is_public
    and (p_category = 'all' or l.category = p_category)
    and (
      nullif(trim(p_search), '') is null
      or l.name ilike '%' || trim(p_search) || '%'
      or l.slug ilike '%' || trim(p_search) || '%'
    );
$$;

grant execute on function public.get_logos(text, integer, integer, text, text, text) to anon, authenticated;
grant execute on function public.get_logo_count(text, text) to anon, authenticated;
